### ISSUE TITLE
On-cell color encoding

### ISSUE THREAD

**Issue by gotdairyya** [multinet-app/view-adjmatrix#49]
Color encoding of an attribute
![image](https://user-images.githubusercontent.com/8480871/80751748-96c82900-8ae7-11ea-85aa-269621a22001.png)

**Comment by waxlamp** [comment]
I think this can start out as simply displaying a colormapped attribute from the edge data or one (or both) of the connected nodes.

In the future we can add a new issue to handle things like aggregated nodes, or a more general function of node/edge data (i.e. path length, etc.).
