### ISSUE TITLE
Fix TypeError on Load

### ISSUE THREAD

**Issue by gotdairyya** [multinet-app/view-adjmatrix#71]
When uploading flights dataset, getting a `TypeError: Cannot read property 'neighbors' of undefined`

@JackWilb

**Comment by JackWilb** [comment]
There are a couple issues. The main is that we do `.filter()[0]` and the filter can sometimes be empty

**Comment by JackWilb** [comment]
This is fixed by not loading tables that are too large. It currently errors out in a different way
